name = "ami-letter"
compatibility_date = "2026-08-28"
main = "./_worker.js"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ami-letter-db"
database_id = "cb378f1b-fc35-4e2a-95a3-74132373ed78"
